# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '测试HookZZ-MD' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 测试HookZZ-MD

end

target '测试HookZZ-MDDylib' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 测试HookZZ-MDDylib

end
